[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --ignore-scripts"]

[phases.build]
cmds = ["pnpm exec prisma generate", "pnpm build"]

[start]
cmd = "pnpm start"
